#!/bin/bash

cat correct > checker_output
((i=0))

while diff -w checker_output correct
do
	./gen > input
	#./pavic_brute < input > official
	./pavic < input > output
	./checker input output output > checker_output
	echo $i
	((i=i+1))
done
