#!/bin/bash

cat correct > checker_output
((i=0))

while diff -w checker_output correct
do
	./gen > input
	./pavic < input > official
	./$1 < input > output
	./checker input official output > checker_output
	echo $i
	((i=i+1))
done
